apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: le-prod
    metallb.io/address-pool: public-pool
  name: aethericforge-web
  namespace: aetheric-forge
spec:
  ingressClassName: nginx
  rules:
  - host: www-dev.aethericforge.ca
    http:
      paths:
      - backend:
          service:
            name: aethericforge-web
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: www.aethericforge.ca
    http:
      paths:
      - backend:
          service:
            name: aethericforge-web
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: aethericforge.ca
    http:
      paths:
      - backend:
          service:
            name: aethericforge-web
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - www-dev.aethericforge.ca
    - www.aethericforge.ca
    - aethericforge.ca
    secretName: aethericforge-web-tls
