apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aetheric-provisioning-worker-data
  namespace: aetheric-forge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
