apiVersion: apps/v1
kind: Deployment
metadata:
  name: aethericforge-web
  namespace: aetheric-forge
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aethericforge-web
  template:
    metadata:
      labels:
        app: aethericforge-web
    spec:
      containers:
      - env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
          value: "true"
        - name: SSL_CERT_FILE
          value: /var/run/aetheric-forge/trust/ca.crt
        envFrom:
        - secretRef:
            name: aethericforge-web-config
        image: ghcr.io/aetheric-forge/aethericforge-web:sha-cd7b59a@sha256:dfc0fc5a8041aba5e45c6d0c2130ffc1712d2476fb734b44c16c20d072c45aaf
        imagePullPolicy: Always
        name: aethericforge-web
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /data
          name: web-signin-data
        - mountPath: /var/run/aetheric-forge/trust
          name: step-ca-root-ca
          readOnly: true
      volumes:
      - name: web-signin-data
        persistentVolumeClaim:
          claimName: aethericforge-web-signin-data
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: step-ca-root-ca
        name: step-ca-root-ca

