apiVersion: apps/v1
kind: Deployment

metadata:
  name: aethericforge-web
  namespace: aetheric-forge

spec:
  replicas: 1

  selector:
    matchLabels:
      app: aethericforge-web

  template:
    metadata:
      labels:
        app: aethericforge-web

    spec:
      containers:
        - name: aethericforge-web

          image: ghcr.io/aetheric-forge/aethericforge-web:v0.3.0

          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
              value: "true"
            - name: SSL_CERT_FILE
              value: /var/run/aetheric-forge/trust/ca.crt

          envFrom:
            - secretRef:
                name: aethericforge-web-config

          resources:
            requests:
              cpu: 50m
              memory: 128Mi

            limits:
              cpu: 500m
              memory: 512Mi

          volumeMounts:
            - name: step-ca-root-ca
              mountPath: /var/run/aetheric-forge/trust
              readOnly: true
      volumes:
        - name: step-ca-root-ca
          configMap:
            name: step-ca-root-ca
            items:
              - key: ca.crt
                path: ca.crt

