apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-ca
  namespace: aetheric-forge
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBpzCCAU2gAwIBAgIUSIQNS0pEGmqRsCIIedcmXyS3A84wCgYIKoZIzj0EAwIw
    ITEfMB0GA1UEAwwWQWV0aGVyaWMgRm9yZ2UgUm9vdCBDQTAeFw0yNjA2MjIyMDE0
    NDFaFw00NjA2MTcyMDE0NDFaMCExHzAdBgNVBAMMFkFldGhlcmljIEZvcmdlIFJv
    b3QgQ0EwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARn6dcYXuerS5eZXfrvalaO
    BS530ux9BrNSUR5Tpn7wW8M7MaBWcZ1yxsQSWOk5tBUjlvTYGFkJ+dIRwQjlkKXK
    o2MwYTAdBgNVHQ4EFgQUb4RG/HF8QPn7V/BuQc4vF0JuPNIwHwYDVR0jBBgwFoAU
    b4RG/HF8QPn7V/BuQc4vF0JuPNIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
    BAMCAQYwCgYIKoZIzj0EAwIDSAAwRQIgdzZ10CPr91QvcQpjFVIfZzuEQnlFSryh
    EaroM+KRF5UCIQCyBvizoMvqrwjwdYBFyPUOr0+YsrlCPmEhiiDG1X5p5A==
    -----END CERTIFICATE-----
