apiVersion: v1
kind: ConfigMap
metadata:
  name: step-ca-root-ca
  namespace: aetheric-forge
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBvTCCAWOgAwIBAgIUUv9CIApvFM38CqzZbSMd2awHkcIwCgYIKoZIzj0EAwIw
    LDEqMCgGA1UEAwwhQmxhY2sgQ2lyY3VpdCBEZXNpZ24gSW5jLiBSb290IENBMB4X
    DTI2MTAwMjE2NTY0N1oXDTM2MDkyOTE2NTY0N1owLDEqMCgGA1UEAwwhQmxhY2sg
    Q2lyY3VpdCBEZXNpZ24gSW5jLiBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0D
    AQcDQgAEs8jCiLMKxjyKhjCeTdK9+ENKwikULi3thAfEBVuj/RBx1tD08MMvgtb1
    1HBo/9swsWpkX0JvBFLkKQbul0OPkaNjMGEwHwYDVR0jBBgwFoAUxS5G08QsvjrE
    0WW9l2DQPV04Nf0wDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYwHQYD
    VR0OBBYEFMUuRtPELL46xNFlvZdg0D1dODX9MAoGCCqGSM49BAMCA0gAMEUCIEpg
    u5ooIBM+QBIX1B126tWyY37u9LxMC1yB7AYvJJ+LAiEA3OjRlpNDoscAkRaNiM4X
    /GGghQEk4rHUqg5MWe1UHlw=
    -----END CERTIFICATE-----
